from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

def validate_preprocessing_inputs(X, column_types):
    """
    Validate that X and column_types are compatible
    with the ML preprocessing pipeline.
    """

    if X is None:
        raise ValueError("Feature dataset cannot be None.")

    if X.empty:
        raise ValueError("Feature dataset cannot be empty.")

    missing_column_types = [
        column
        for column in X.columns
        if column not in column_types
    ]

    if missing_column_types:
        raise ValueError(
            f"Missing semantic types for columns: {missing_column_types}"
        )

    supported_types = {
        "numerical",
        "binary",
        "categorical",
        "identifier",
        "text",
        "datetime"
    }

    unsupported_types = {
        column_types[column]
        for column in X.columns
        if column_types[column] not in supported_types
    }

    if unsupported_types:
        raise ValueError(
            f"Unsupported semantic column types: {unsupported_types}"
        )

    usable_columns = [
        column
        for column in X.columns
        if column_types[column] in {
            "numerical",
            "binary",
            "categorical"
        }
    ]

    if not usable_columns:
        raise ValueError(
            "No usable feature columns available for ML preprocessing."
        )

    return True


def get_feature_columns(X, column_types):
    """
    Get feature columns grouped by their semantic type.
    """

    numerical_columns = []
    binary_columns = []
    categorical_columns = []

    for column in X.columns:
        column_type = column_types[column]

        if column_type == "numerical":
            numerical_columns.append(column)

        elif column_type == "binary":
            binary_columns.append(column)

        elif column_type == "categorical":
            categorical_columns.append(column)

    return numerical_columns, binary_columns, categorical_columns


def build_preprocessor(X,column_types):
    """
    Build an ML preprocessing pipeline based on semantic column types.
    """

    validate_preprocessing_inputs(X, column_types)

    numeric, binary, categorical = get_feature_columns(X,column_types)

    numerical_pipeline = Pipeline(steps=[ ("imputer", SimpleImputer(strategy="median")), ("scaler",StandardScaler())])
    binary_pipeline = Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("encoder",OrdinalEncoder(handle_unknown="use_encoded_value",unknown_value=-1))])
    categorical_pipeline = Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("encoder",OneHotEncoder(handle_unknown="ignore"))])

    transform = []

    if numeric:
        transform.append(("numerical",numerical_pipeline,numeric))
    if binary:
        transform.append(("binary",binary_pipeline,binary))
    if categorical:
        transform.append(("categorical",categorical_pipeline,categorical))

    if not transform:
        raise ValueError("No supported feature columns available for ML preprocessing.")

    preprocessor = ColumnTransformer(transformers=transform, remainder="drop")

    return preprocessor


def get_processed_feature_names(preprocessor):
    """
    Return the feature names generated by the fitted preprocessor.
    """
    return preprocessor.get_feature_names_out().tolist()


def get_preprocessing_metadata(X,column_types):
    """
    Return information about how each feature group will be processed.
    """
    numerical_columns, binary_columns, categorical_columns = get_feature_columns(X, column_types)
    ignored_columns = [ column for column in X.columns if column_types[column] in ["identifier","text","datetime"]]

    return { "numerical_columns": numerical_columns,"binary_columns": binary_columns,"categorical_columns": categorical_columns,"ignored_columns": ignored_columns}


def preprocess_train_test(X_train, X_test, column_types):
    """
    Fit the preprocessor using training data and transform
    both training and testing data.
    """
    validate_preprocessing_inputs(X_train, column_types)
    validate_preprocessing_inputs(X_test, column_types)

    preprocessor = build_preprocessor(X_train, column_types)

    X_train_processed = preprocessor.fit_transform(X_train)

    X_test_processed = preprocessor.transform(X_test)

    feature_names = get_processed_feature_names(preprocessor)

    metadata = get_preprocessing_metadata(X_train, column_types)

    return ( X_train_processed, X_test_processed, preprocessor, feature_names, metadata)